<a href="https://colab.research.google.com/github/ketannehra9/Data-Science-Guided-Projects/blob/main/GP_Python_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL NUMPY ARRAYS**

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# created a 1d list of numbers
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
print(list_1)

# converted that list of number to a 1d np array
np_array_1 = np.array(list_1)
print(np_array_1)
type(np_array_1)

# defining a 2d np array
np_array_2 = np.array([
    [1,2,3],
    [2,4,6],
    [3,9,12]
])
np_array_2

# mini-challenge-1
mc_1 = np.array([
    [3, 7, 9, 3],
    [4, 3, 2, 2]
])
mc_1

[50, 60, 80, 100, 200, 300, 500, 600]
[ 50  60  80 100 200 300 500 600]

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

**TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS¶**

In [ ]:
rand = np.random.rand(20)
rand

rand_matrix = np.random.rand(3, 3)
rand_matrix

rand_int = np.random.randint(1,50)
rand_int

rand_int_array = np.random.randint(1,10,15)
rand_int_array

x = np.arange(1,50)
x

id_mat = np.eye(7)
#print(id_mat)

one_mat = np.ones((4,5))
#print(one_mat)

zero_mat = np.zeros((8))
#print(zero_mat)

# mini-challenge-2
x = int(input("Enter positive integer: "))
arr = np.random.randint(0, x, 10)
print(arr)

Enter positive integer: 5
[3 0 4 3 2 3 3 1 3 3]

**TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY**

In [ ]:
x = np.arange(1,10)
y = np.arange(1,10)
sum = x + y
sum

sq_x = x ** 2
sq_x

sqrt_x = np.sqrt(sq_x)
sqrt_x

z = np.exp(y)
z

# mini-challenge-3
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

d = x - y
d_sq = d ** 2
d_sum = np.sum(d_sq)

dist = np.sqrt(d_sum)
dist

np.float64(18.33030277982336)

**TASK #4: PERFORM ARRAYS SLICING AND INDEXING**

In [ ]:
my_np_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_np_array

my_np_array[0]
my_np_array[-1]

# slicing
sliced = my_np_array[0:3]
sliced

# broadcasting
my_np_array[0:4] = 7
my_np_array


matrix = np.random.randint(1,10, (4,4))
matrix

matrix[0]
matrix[0][1]

# mini-challenge-4
mat = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]
])
mat[-1] = 0
mat

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)**

In [ ]:
mat = np.random.randint(1,10,(5,5))
mat

new_mat = matrix[matrix>7]
new_mat


#mini-challenge-5
matrix = np.array([
    [2, 30 ,20, -2, -4],
    [3 ,4  ,40 ,-3 ,-2],
    [-3, 4 ,-6 ,90 ,10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]
])
matrix[matrix < 0] = 0
matrix[matrix%2 != 0] = -2

matrix

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

**TASK #6: UNDERSTAND PANDAS FUNDAMENTALS**

In [ ]:
bank_client_df = pd.DataFrame({
    'Bank Client ID': [11,12,13,14],
    'Bank Client Name':['Jim', 'Pam', 'Mike', 'Andy'],
    'Net Worth [$]':[2500, 350000, 10000, 90000],
    'Years with Bank': [5, 6, 1, 9]
})

bank_client_df
bank_client_df.head(2)

#mini-challenge-6

portfolio_df = pd.DataFrame({
    'Stocks': ['APL', 'BKS', 'JPM'],
    'No. of shares': [59, 399, 733],
    'Price per share': [49, 20, 58]
})
print(portfolio_df)
total_value = sum(portfolio_df['No. of shares'] * portfolio_df['Price per share'])
print(f'Total value = ${total_value}')

  Stocks  No. of shares  Price per share
0    APL             59               49
1    BKS            399               20
2    JPM            733               58
Total value = $53385

**TASK #7: PANDAS WITH CSV AND HTML DATA**

In [7]:
# Reading HTML Data (web-scraping)
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[1]

# mini-challenge-7

,Province,Average House Price,12 Month Change
0,British Columbia,"$736,000",+ 7.6 %
1,Ontario,"$594,000",– 3.2 %
2,Alberta,"$353,000",– 7.5 %
3,Quebec,"$340,000",+ 7.6 %
4,Manitoba,"$295,000",– 1.4 %
5,Saskatchewan,"$271,000",– 3.8 %
6,Nova Scotia,"$266,000",+ 3.5 %
7,Prince Edward Island,"$243,000",+ 3.0 %
8,Newfoundland / Labrador,"$236,000",– 1.6 %
9,New Brunswick,"$183,000",– 2.2 %
10,Canadian Average,"$488,000",– 1.3 %
11,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

In [8]:
import requests
from bs4 import BeautifulSoup

url = "https://www.w3schools.com/html/html_examples.html"

# get page
response = requests.get(url)

# parse HTML
soup = BeautifulSoup(response.text, "html.parser")

# find all links
links = soup.find_all("a")

# print link text and URL
for link in links:
    print(link.text.strip(), "->", link.get("href"))

 -> https://www.w3schools.com
home page -> /default.asp

**TASK #8: PANDAS OPERATIONS**

In [ ]:
bank_client_df = pd.DataFrame({
    'Bank Client ID': [11,12,13,14],
    'Bank Client Name':['Jim', 'Pam', 'Mike', 'Andy'],
    'Net Worth [$]':[2500, 350000, 10000, 90000],
    'Years with Bank': [5, 6, 1, 9]
})

bank_client_df
bank_client_df.head(2)

# SELECTION
df_loyal = bank_client_df[bank_client_df['Years with Bank'] >= 5]
df_loyal

# DELETION
del bank_client_df['Bank Client ID']
bank_client_df

# mini-challenge-8
hni_df = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]
print(hni_df)

combined_nw = sum(hni_df['Net Worth [$]'])
print(f'Combined HNI NW = {combined_nw}')

  Bank Client Name  Net Worth [$]  Years with Bank
1              Pam         350000                6
2             Mike          10000                1
3             Andy          90000                9
Combined HNI NW = 450000

**TASK #9: PANDAS WITH FUNCTIONS**

In [ ]:
bank_client_df = pd.DataFrame({
    'Bank Client ID': [11,12,13,14],
    'Bank Client Name':['Jim', 'Pam', 'Mike', 'Andy'],
    'Net Worth [$]':[2500, 350000, 10000, 90000],
    'Years with Bank': [5, 6, 1, 9]
})

bank_client_df

def networth_update(balance):
  return 1.2 * balance

bank_client_df['Net Worth [$]'].apply(networth_update)

# mini-challenge-9


def nw_update(price):
  return 3 * price + 200

results = bank_client_df['Net Worth [$]'].apply(nw_update)
display(results)

display(results.sum())

0       7700
1    1050200
2      30200
3     270200
Name: Net Worth [$], dtype: int64

np.int64(1358300)

**TASK #10: PERFORM SORTING AND ORDERING IN PANDAS**

In [ ]:
bank_client_df = pd.DataFrame({
    'Bank Client ID': [11,12,13,14],
    'Bank Client Name':['Jim', 'Pam', 'Mike', 'Andy'],
    'Net Worth [$]':[2500, 350000, 10000, 90000],
    'Years with Bank': [5, 6, 1, 9]
})

# sorting with criteria (copy)
bank_client_df.sort_values(by = 'Years with Bank')

# sorting with criteria (in-place)
bank_client_df.sort_values(by = 'Years with Bank', inplace=True)

bank_client_df

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
2              13             Mike          10000                1
0              11              Jim           2500                5
1              12              Pam         350000                6
3              14             Andy          90000                9

**TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS**

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1','A2', 'A3'],
    'B': ['B0', 'B1','B2', 'B3'],
    'C': ['C0', 'C1','C2', 'C3'],
    'D': ['D0', 'D1','D2', 'D3']
},  index = [0,1,2,3])

df2 = pd.DataFrame({
    'A': ['A4', 'A5','A6', 'A7'],
    'B': ['B4', 'B5','B6', 'B7'],
    'C': ['C4', 'C5','C6', 'C7'],
    'D': ['D4', 'D5','D6', 'D7']
},  index = [4,5,6,7])

df3 = pd.DataFrame({
    'A': ['A8', 'A9','A10', 'A11'],
    'B': ['B8', 'B9','B10', 'B11'],
    'C': ['C8', 'C9','C10', 'C11'],
    'D': ['D8', 'D9','D10', 'D11']
},  index = [8,9,10,11])

df_conc = pd.concat([df1, df2, df3])
df_conc

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

**TASK #12: PROJECT AND CONCLUDING REMARKS**

In [ ]:
bank_df_1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'First Name': ['Jim', 'Pam', 'Michael', 'Dwight', 'Angela'],
    'Last Name': ['Halpert', 'Beesly', 'Scott', 'Schrute', 'Martin']
    })

print(bank_df_1)

bank_df_2 = pd.DataFrame({
    'ID': [6, 7, 8, 9, 10],
    'First Name': ['Harvey', 'Mike', 'Jessica', 'Donna', 'Sean'],
    'Last Name': ['Specter', 'Ross', 'Pearson', 'Paulsen', 'Cahil']

})
print(bank_df_2)

annual_salary = pd.DataFrame({
    'ID': [1,2,3,4,5,6, 7, 8, 9, 10],
    'Salary':[9000, 12000, 3000, 5000, 4000, 8000, 6500, 7000, 9000, 10000]
})
print(annual_salary)

bank_df = pd.concat([bank_df_1, bank_df_2])
print(bank_df)

bank_df_merged = pd.merge(bank_df, annual_salary, on = 'ID')
print(bank_df_merged)

new_client = pd.DataFrame({
    'ID': [11],
    'First Name': ['Ketan'],
    'Last Name': ['Nehra'],
    'Salary': [8000]
})

print(new_client)

bank_df_final = pd.concat([bank_df_merged, new_client])
print(bank_df_final)

   ID First Name Last Name
0   1        Jim   Halpert
1   2        Pam    Beesly
2   3    Michael     Scott
3   4     Dwight   Schrute
4   5     Angela    Martin
   ID First Name Last Name
0   6     Harvey   Specter
1   7       Mike      Ross
2   8    Jessica   Pearson
3   9      Donna   Paulsen
4  10       Sean     Cahil
   ID  Salary
0   1    9000
1   2   12000
2   3    3000
3   4    5000
4   5    4000
5   6    8000
6   7    6500
7   8    7000
8   9    9000
9  10   10000
   ID First Name Last Name
0   1        Jim   Halpert
1   2        Pam    Beesly
2   3    Michael     Scott
3   4     Dwight   Schrute
4   5     Angela    Martin
0   6     Harvey   Specter
1   7       Mike      Ross
2   8    Jessica   Pearson
3   9      Donna   Paulsen
4  10       Sean     Cahil
   ID First Name Last Name  Salary
0   1        Jim   Halpert    9000
1   2        Pam    Beesly   12000
2   3    Michael     Scott    3000
3   4     Dwight   Schrute    5000
4   5     Angela    Martin    4000
5   6     Harvey   Specter    8000
6   7       Mike      Ross    6500
7   8    Jessica   Pearson    7000
8   9      Donna   Paulsen    9000
9  10       Sean     Cahil   10000
   ID First Name Last Name  Salary
0  11      Ketan     Nehra    8000
   ID First Name Last Name  Salary
0   1        Jim   Halpert    9000
1   2        Pam    Beesly   12000
2   3    Michael     Scott    3000
3   4     Dwight   Schrute    5000
4   5     Angela    Martin    4000
5   6     Harvey   Specter    8000
6   7       Mike      Ross    6500
7   8    Jessica   Pearson    7000
8   9      Donna   Paulsen    9000
9  10       Sean     Cahil   10000
0  11      Ketan     Nehra    8000